//! QASM (Quantum Assembly Language) export functionality
//!
//! This module provides support for exporting quantum circuits to OpenQASM 2.0 and 3.0 formats,
//! enabling interoperability with other quantum computing platforms and simulators.

use crate::error::{MyQuatError, Result};
use crate::gate_decomposition::arbitrary_rotation_to_zyz;
use crate::gates_extended::ExtendedGate;
use crate::{Parameter, QuantumCircuit, StandardGate};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fmt::Write;

/// QASM export configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QasmConfig {
    /// QASM version to export (2.0 or 3.0)
    pub version: QasmVersion,
    /// Include comments in output
    pub include_comments: bool,
    /// Use custom gate definitions
    pub use_custom_gates: bool,
    /// Include extended gate definitions
    pub include_extended_gates: bool,
    /// Precision for floating point numbers
    pub precision: usize,
    /// Include measurement operations
    pub include_measurements: bool,
}

impl Default for QasmConfig {
    fn default() -> Self {
        QasmConfig {
            version: QasmVersion::V2_0,
            include_comments: true,
            use_custom_gates: false,
            include_extended_gates: true,
            precision: 6,
            include_measurements: true,
        }
    }
}

/// QASM version specification
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum QasmVersion {
    /// OpenQASM 2.0
    V2_0,
    /// OpenQASM 3.0
    V3_0,
}

impl std::fmt::Display for QasmVersion {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            QasmVersion::V2_0 => write!(f, "2.0"),
            QasmVersion::V3_0 => write!(f, "3.0"),
        }
    }
}

/// QASM exporter for quantum circuits
pub struct QasmExporter {
    /// Export configuration
    config: QasmConfig,
}

impl QasmExporter {
    /// Create a new QASM exporter with default configuration
    pub fn new() -> Self {
        QasmExporter {
            config: QasmConfig::default(),
        }
    }

    /// Create a new QASM exporter with custom configuration
    pub fn with_config(config: QasmConfig) -> Self {
        QasmExporter { config }
    }

    /// Export a quantum circuit to QASM string
    pub fn export(&self, circuit: &QuantumCircuit) -> Result<String> {
        match self.config.version {
            QasmVersion::V2_0 => self.export_v2(circuit),
            QasmVersion::V3_0 => self.export_v3(circuit),
        }
    }

    /// Export to OpenQASM 2.0 format
    fn export_v2(&self, circuit: &QuantumCircuit) -> Result<String> {
        let mut output = String::new();

        // Header
        writeln!(output, "OPENQASM 2.0;").unwrap();
        writeln!(output, "include \"qelib1.inc\";").unwrap();

        // Add extended gate definitions if enabled
        if self.config.include_extended_gates {
            self.add_extended_gate_definitions_v2(&mut output)?;
        }

        if self.config.include_comments {
            writeln!(output, "// Generated by MyQuat quantum computing library").unwrap();
            if let Some(name) = circuit.name() {
                writeln!(output, "// Circuit: {}", name).unwrap();
            }
            writeln!(output).unwrap();
        }

        // Quantum and classical register declarations
        writeln!(output, "qreg q[{}];", circuit.num_qubits()).unwrap();
        if circuit.num_clbits() > 0 {
            writeln!(output, "creg c[{}];", circuit.num_clbits()).unwrap();
        }
        writeln!(output).unwrap();

        // Gate operations
        for instruction in circuit.data().instructions() {
            if instruction.is_measurement() {
                if self.config.include_measurements && !instruction.clbits.is_empty() {
                    writeln!(
                        output,
                        "measure q[{}] -> c[{}];",
                        instruction.qubits[0].index(),
                        instruction.clbits[0].index()
                    )
                    .unwrap();
                }
            } else {
                let gate_qasm = self.gate_to_qasm_v2(
                    &instruction.gate.gate_type,
                    &instruction.gate.parameters,
                    &instruction.qubits,
                )?;
                writeln!(output, "{}", gate_qasm).unwrap();
            }
        }

        Ok(output)
    }

    /// Export to OpenQASM 3.0 format
    fn export_v3(&self, circuit: &QuantumCircuit) -> Result<String> {
        let mut output = String::new();

        // Header
        writeln!(output, "OPENQASM 3.0;").unwrap();
        writeln!(output, "include \"stdgates.inc\";").unwrap();

        // Add extended gate definitions if enabled
        if self.config.include_extended_gates {
            self.add_extended_gate_definitions_v3(&mut output)?;
        }

        if self.config.include_comments {
            writeln!(output, "// Generated by MyQuat quantum computing library").unwrap();
            if let Some(name) = circuit.name() {
                writeln!(output, "// Circuit: {}", name).unwrap();
            }
            writeln!(output).unwrap();
        }

        // Quantum and classical register declarations
        writeln!(output, "qubit[{}] q;", circuit.num_qubits()).unwrap();
        if circuit.num_clbits() > 0 {
            writeln!(output, "bit[{}] c;", circuit.num_clbits()).unwrap();
        }
        writeln!(output).unwrap();

        // Gate operations
        for instruction in circuit.data().instructions() {
            if instruction.is_measurement() {
                if self.config.include_measurements && !instruction.clbits.is_empty() {
                    writeln!(
                        output,
                        "c[{}] = measure q[{}];",
                        instruction.clbits[0].index(),
                        instruction.qubits[0].index()
                    )
                    .unwrap();
                }
            } else {
                let gate_qasm = self.gate_to_qasm_v3(
                    &instruction.gate.gate_type,
                    &instruction.gate.parameters,
                    &instruction.qubits,
                )?;
                writeln!(output, "{}", gate_qasm).unwrap();
            }
        }

        Ok(output)
    }

    /// Convert a gate to QASM 2.0 representation
    fn gate_to_qasm_v2(
        &self,
        gate: &StandardGate,
        params: &[Parameter],
        qubits: &[crate::circuit::Qubit],
    ) -> Result<String> {
        let qubit_str = qubits
            .iter()
            .map(|q| format!("q[{}]", q.index()))
            .collect::<Vec<_>>()
            .join(",");

        match gate {
            StandardGate::I => Ok(format!("id {};", qubit_str)),
            StandardGate::X => Ok(format!("x {};", qubit_str)),
            StandardGate::Y => Ok(format!("y {};", qubit_str)),
            StandardGate::Z => Ok(format!("z {};", qubit_str)),
            StandardGate::H => Ok(format!("h {};", qubit_str)),
            StandardGate::S => Ok(format!("s {};", qubit_str)),
            StandardGate::Sdg => Ok(format!("sdg {};", qubit_str)),
            StandardGate::T => Ok(format!("t {};", qubit_str)),
            StandardGate::Tdg => Ok(format!("tdg {};", qubit_str)),
            StandardGate::Rx => {
                if params.is_empty() {
                    return Err(MyQuatError::circuit_error(
                        "RX gate requires angle parameter",
                    ));
                }
                let angle = self.format_parameter(&params[0])?;
                Ok(format!("rx({}) {};", angle, qubit_str))
            }
            StandardGate::Ry => {
                if params.is_empty() {
                    return Err(MyQuatError::circuit_error(
                        "RY gate requires angle parameter",
                    ));
                }
                let angle = self.format_parameter(&params[0])?;
                Ok(format!("ry({}) {};", angle, qubit_str))
            }
            StandardGate::Rz => {
                if params.is_empty() {
                    return Err(MyQuatError::circuit_error(
                        "RZ gate requires angle parameter",
                    ));
                }
                let angle = self.format_parameter(&params[0])?;
                Ok(format!("rz({}) {};", angle, qubit_str))
            }
            StandardGate::P => {
                if params.is_empty() {
                    return Err(MyQuatError::circuit_error(
                        "Phase gate requires angle parameter",
                    ));
                }
                let angle = self.format_parameter(&params[0])?;
                Ok(format!("p({}) {};", angle, qubit_str))
            }
            StandardGate::U => {
                if params.len() < 3 {
                    return Err(MyQuatError::circuit_error("U gate requires 3 parameters"));
                }
                let theta = self.format_parameter(&params[0])?;
                let phi = self.format_parameter(&params[1])?;
                let lambda = self.format_parameter(&params[2])?;
                Ok(format!("u({},{},{}) {};", theta, phi, lambda, qubit_str))
            }
            StandardGate::U1 => {
                if params.is_empty() {
                    return Err(MyQuatError::circuit_error(
                        "U1 gate requires lambda parameter",
                    ));
                }
                let lambda = self.format_parameter(&params[0])?;
                Ok(format!("u1({}) {};", lambda, qubit_str))
            }
            StandardGate::U2 => {
                if params.len() < 2 {
                    return Err(MyQuatError::circuit_error("U2 gate requires 2 parameters"));
                }
                let phi = self.format_parameter(&params[0])?;
                let lambda = self.format_parameter(&params[1])?;
                Ok(format!("u2({},{}) {};", phi, lambda, qubit_str))
            }
            StandardGate::U3 => {
                if params.len() < 3 {
                    return Err(MyQuatError::circuit_error("U3 gate requires 3 parameters"));
                }
                let theta = self.format_parameter(&params[0])?;
                let phi = self.format_parameter(&params[1])?;
                let lambda = self.format_parameter(&params[2])?;
                Ok(format!("u3({},{},{}) {};", theta, phi, lambda, qubit_str))
            }
            StandardGate::CX => Ok(format!("cx {};", qubit_str)),
            StandardGate::CY => Ok(format!("cy {};", qubit_str)),
            StandardGate::CZ => Ok(format!("cz {};", qubit_str)),
            StandardGate::CH => Ok(format!("ch {};", qubit_str)),
            StandardGate::CRx => {
                if params.is_empty() {
                    return Err(MyQuatError::circuit_error(
                        "CRX gate requires angle parameter",
                    ));
                }
                let angle = self.format_parameter(&params[0])?;
                Ok(format!("crx({}) {};", angle, qubit_str))
            }
            StandardGate::CRy => {
                if params.is_empty() {
                    return Err(MyQuatError::circuit_error(
                        "CRY gate requires angle parameter",
                    ));
                }
                let angle = self.format_parameter(&params[0])?;
                Ok(format!("cry({}) {};", angle, qubit_str))
            }
            StandardGate::CRz => {
                if params.is_empty() {
                    return Err(MyQuatError::circuit_error(
                        "CRZ gate requires angle parameter",
                    ));
                }
                let angle = self.format_parameter(&params[0])?;
                Ok(format!("crz({}) {};", angle, qubit_str))
            }
            StandardGate::CP => {
                if params.is_empty() {
                    return Err(MyQuatError::circuit_error(
                        "CP gate requires angle parameter",
                    ));
                }
                let angle = self.format_parameter(&params[0])?;
                Ok(format!("cp({}) {};", angle, qubit_str))
            }
            StandardGate::Swap => Ok(format!("swap {};", qubit_str)),
            StandardGate::CCX => Ok(format!("ccx {};", qubit_str)),
            StandardGate::CSwap => Ok(format!("cswap {};", qubit_str)),
            _ => Err(MyQuatError::circuit_error(format!(
                "Gate {:?} not supported in QASM 2.0",
                gate
            ))),
        }
    }

    /// Convert a gate to QASM 3.0 representation
    fn gate_to_qasm_v3(
        &self,
        gate: &StandardGate,
        params: &[Parameter],
        qubits: &[crate::circuit::Qubit],
    ) -> Result<String> {
        let qubit_str = qubits
            .iter()
            .map(|q| format!("q[{}]", q.index()))
            .collect::<Vec<_>>()
            .join(", ");

        match gate {
            StandardGate::I => Ok(format!("id {};", qubit_str)),
            StandardGate::X => Ok(format!("x {};", qubit_str)),
            StandardGate::Y => Ok(format!("y {};", qubit_str)),
            StandardGate::Z => Ok(format!("z {};", qubit_str)),
            StandardGate::H => Ok(format!("h {};", qubit_str)),
            StandardGate::S => Ok(format!("s {};", qubit_str)),
            StandardGate::Sdg => Ok(format!("sdg {};", qubit_str)),
            StandardGate::T => Ok(format!("t {};", qubit_str)),
            StandardGate::Tdg => Ok(format!("tdg {};", qubit_str)),
            StandardGate::Rx => {
                if params.is_empty() {
                    return Err(MyQuatError::circuit_error(
                        "RX gate requires angle parameter",
                    ));
                }
                let angle = self.format_parameter(&params[0])?;
                Ok(format!("rx({}) {};", angle, qubit_str))
            }
            StandardGate::Ry => {
                if params.is_empty() {
                    return Err(MyQuatError::circuit_error(
                        "RY gate requires angle parameter",
                    ));
                }
                let angle = self.format_parameter(&params[0])?;
                Ok(format!("ry({}) {};", angle, qubit_str))
            }
            StandardGate::Rz => {
                if params.is_empty() {
                    return Err(MyQuatError::circuit_error(
                        "RZ gate requires angle parameter",
                    ));
                }
                let angle = self.format_parameter(&params[0])?;
                Ok(format!("rz({}) {};", angle, qubit_str))
            }
            StandardGate::P => {
                if params.is_empty() {
                    return Err(MyQuatError::circuit_error(
                        "Phase gate requires angle parameter",
                    ));
                }
                let angle = self.format_parameter(&params[0])?;
                Ok(format!("p({}) {};", angle, qubit_str))
            }
            StandardGate::U => {
                if params.len() < 3 {
                    return Err(MyQuatError::circuit_error("U gate requires 3 parameters"));
                }
                let theta = self.format_parameter(&params[0])?;
                let phi = self.format_parameter(&params[1])?;
                let lambda = self.format_parameter(&params[2])?;
                Ok(format!("u({}, {}, {}) {};", theta, phi, lambda, qubit_str))
            }
            StandardGate::CX => Ok(format!("cx {};", qubit_str)),
            StandardGate::CY => Ok(format!("cy {};", qubit_str)),
            StandardGate::CZ => Ok(format!("cz {};", qubit_str)),
            StandardGate::CH => Ok(format!("ch {};", qubit_str)),
            StandardGate::CRx => {
                if params.is_empty() {
                    return Err(MyQuatError::circuit_error(
                        "CRX gate requires angle parameter",
                    ));
                }
                let angle = self.format_parameter(&params[0])?;
                Ok(format!("crx({}) {};", angle, qubit_str))
            }
            StandardGate::CRy => {
                if params.is_empty() {
                    return Err(MyQuatError::circuit_error(
                        "CRY gate requires angle parameter",
                    ));
                }
                let angle = self.format_parameter(&params[0])?;
                Ok(format!("cry({}) {};", angle, qubit_str))
            }
            StandardGate::CRz => {
                if params.is_empty() {
                    return Err(MyQuatError::circuit_error(
                        "CRZ gate requires angle parameter",
                    ));
                }
                let angle = self.format_parameter(&params[0])?;
                Ok(format!("crz({}) {};", angle, qubit_str))
            }
            StandardGate::CP => {
                if params.is_empty() {
                    return Err(MyQuatError::circuit_error(
                        "CP gate requires angle parameter",
                    ));
                }
                let angle = self.format_parameter(&params[0])?;
                Ok(format!("cp({}) {};", angle, qubit_str))
            }
            StandardGate::Swap => Ok(format!("swap {};", qubit_str)),
            StandardGate::CCX => Ok(format!("ccx {};", qubit_str)),
            StandardGate::CSwap => Ok(format!("cswap {};", qubit_str)),
            _ => Err(MyQuatError::circuit_error(format!(
                "Gate {:?} not supported in QASM 3.0",
                gate
            ))),
        }
    }

    /// Format a parameter for QASM output
    fn format_parameter(&self, param: &Parameter) -> Result<String> {
        match param {
            Parameter::Float(value) => Ok(format!(
                "{:.precision$}",
                value,
                precision = self.config.precision
            )),
            Parameter::Symbol(name) => Ok(name.clone()),
            Parameter::Expression(_) => {
                // For now, try to evaluate the expression
                // In a full implementation, we'd need to handle symbolic expressions
                match param.evaluate(&HashMap::new()) {
                    Ok(value) => Ok(format!(
                        "{:.precision$}",
                        value,
                        precision = self.config.precision
                    )),
                    Err(_) => Err(MyQuatError::circuit_error(
                        "Cannot export symbolic expressions to QASM",
                    )),
                }
            }
        }
    }

    /// Add extended gate definitions for QASM 2.0
    fn add_extended_gate_definitions_v2(&self, output: &mut String) -> Result<()> {
        writeln!(output, "// Extended gate definitions").unwrap();

        // Square root gates
        writeln!(output, "gate sqrtx q {{ u2(0, pi) q; }}").unwrap();
        writeln!(output, "gate sqrty q {{ u2(pi/2, pi/2) q; }}").unwrap();
        writeln!(output, "gate sqrtz q {{ u1(pi/2) q; }}").unwrap();
        writeln!(output, "gate sqrth q {{ ry(pi/4) q; }}").unwrap();

        // Two-qubit rotation gates
        writeln!(
            output,
            "gate rxx(theta) a,b {{ h a; h b; cx a,b; rz(theta) b; cx a,b; h a; h b; }}"
        )
        .unwrap();
        writeln!(output, "gate ryy(theta) a,b {{ rx(pi/2) a; rx(pi/2) b; cx a,b; rz(theta) b; cx a,b; rx(-pi/2) a; rx(-pi/2) b; }}").unwrap();
        writeln!(
            output,
            "gate rzz(theta) a,b {{ cx a,b; rz(theta) b; cx a,b; }}"
        )
        .unwrap();
        writeln!(
            output,
            "gate rzx(theta) a,b {{ h b; cx a,b; rz(theta) b; cx a,b; h b; }}"
        )
        .unwrap();

        writeln!(output).unwrap();
        Ok(())
    }

    /// Add extended gate definitions for QASM 3.0
    fn add_extended_gate_definitions_v3(&self, output: &mut String) -> Result<()> {
        writeln!(output, "// Extended gate definitions").unwrap();

        // Square root gates
        writeln!(output, "gate sqrtx q {{ u2(0, π) q; }}").unwrap();
        writeln!(output, "gate sqrty q {{ u2(π/2, π/2) q; }}").unwrap();
        writeln!(output, "gate sqrtz q {{ u1(π/2) q; }}").unwrap();
        writeln!(output, "gate sqrth q {{ ry(π/4) q; }}").unwrap();

        // Two-qubit rotation gates
        writeln!(output, "gate rxx(theta) a, b {{").unwrap();
        writeln!(output, "    h a; h b;").unwrap();
        writeln!(output, "    cx a, b;").unwrap();
        writeln!(output, "    rz(theta) b;").unwrap();
        writeln!(output, "    cx a, b;").unwrap();
        writeln!(output, "    h a; h b;").unwrap();
        writeln!(output, "}}").unwrap();

        writeln!(output, "gate ryy(theta) a, b {{").unwrap();
        writeln!(output, "    rx(π/2) a; rx(π/2) b;").unwrap();
        writeln!(output, "    cx a, b;").unwrap();
        writeln!(output, "    rz(theta) b;").unwrap();
        writeln!(output, "    cx a, b;").unwrap();
        writeln!(output, "    rx(-π/2) a; rx(-π/2) b;").unwrap();
        writeln!(output, "}}").unwrap();

        writeln!(output, "gate rzz(theta) a, b {{").unwrap();
        writeln!(output, "    cx a, b;").unwrap();
        writeln!(output, "    rz(theta) b;").unwrap();
        writeln!(output, "    cx a, b;").unwrap();
        writeln!(output, "}}").unwrap();

        writeln!(output, "gate rzx(theta) a, b {{").unwrap();
        writeln!(output, "    h b;").unwrap();
        writeln!(output, "    cx a, b;").unwrap();
        writeln!(output, "    rz(theta) b;").unwrap();
        writeln!(output, "    cx a, b;").unwrap();
        writeln!(output, "    h b;").unwrap();
        writeln!(output, "}}").unwrap();

        writeln!(output).unwrap();
        Ok(())
    }

    /// Convert an extended gate to QASM representation
    pub fn extended_gate_to_qasm(
        &self,
        gate: &ExtendedGate,
        qubits: &[crate::circuit::Qubit],
    ) -> Result<String> {
        let qubit_str = qubits
            .iter()
            .map(|q| format!("q[{}]", q.index()))
            .collect::<Vec<_>>()
            .join(if self.config.version == QasmVersion::V3_0 {
                ", "
            } else {
                ","
            });

        match gate {
            ExtendedGate::SqrtX => Ok(format!("sqrtx {};", qubit_str)),
            ExtendedGate::SqrtY => Ok(format!("sqrty {};", qubit_str)),
            ExtendedGate::SqrtZ => Ok(format!("sqrtz {};", qubit_str)),
            ExtendedGate::SqrtH => Ok(format!("sqrth {};", qubit_str)),

            ExtendedGate::R(nx, ny, nz) => {
                // Convert arbitrary axis rotation to ZYZ decomposition
                // R(nx, ny, nz) = Rz(φ) Ry(θ) Rz(λ)
                let norm = (nx * nx + ny * ny + nz * nz).sqrt();

                if norm < 1e-10 {
                    // Zero rotation - identity gate
                    Ok(format!("id {};", qubit_str))
                } else {
                    // Normalize and decompose using ZYZ
                    let angle = norm;
                    let nx_norm = nx / norm;
                    let ny_norm = ny / norm;
                    let nz_norm = nz / norm;

                    match arbitrary_rotation_to_zyz(nx_norm, ny_norm, nz_norm, angle) {
                        Ok(angles) => {
                            // Export as Rz(φ) Ry(θ) Rz(λ) sequence
                            let mut result = String::new();

                            if self.config.include_comments {
                                writeln!(
                                    result,
                                    "// R({:.3}, {:.3}, {:.3}) decomposition",
                                    nx, ny, nz
                                )
                                .unwrap();
                            }

                            // First Rz(φ)
                            if angles.phi.abs() > 1e-10 {
                                let phi_str = format!(
                                    "{:.precision$}",
                                    angles.phi,
                                    precision = self.config.precision
                                );
                                writeln!(result, "rz({}) {};", phi_str, qubit_str).unwrap();
                            }

                            // Ry(θ)
                            if angles.theta.abs() > 1e-10 {
                                let theta_str = format!(
                                    "{:.precision$}",
                                    angles.theta,
                                    precision = self.config.precision
                                );
                                writeln!(result, "ry({}) {};", theta_str, qubit_str).unwrap();
                            }

                            // Second Rz(λ)
                            if angles.lambda.abs() > 1e-10 {
                                let lambda_str = format!(
                                    "{:.precision$}",
                                    angles.lambda,
                                    precision = self.config.precision
                                );
                                writeln!(result, "rz({}) {};", lambda_str, qubit_str).unwrap();
                            }

                            // Remove trailing newline
                            if result.ends_with('\n') {
                                result.pop();
                            }

                            Ok(result)
                        }
                        Err(e) => {
                            // Fallback to simple rotation if decomposition fails
                            Err(MyQuatError::circuit_error(format!(
                                "Failed to decompose R gate: {}",
                                e
                            )))
                        }
                    }
                }
            }

            ExtendedGate::GlobalPhase(phase) => {
                let formatted_phase =
                    format!("{:.precision$}", phase, precision = self.config.precision);
                if self.config.version == QasmVersion::V3_0 {
                    Ok(format!("gphase({});", formatted_phase))
                } else {
                    // Global phase has no effect in QASM 2.0, use comment
                    Ok(format!("// Global phase: {}", formatted_phase))
                }
            }

            ExtendedGate::PhaseShift(phase) => {
                let formatted_phase =
                    format!("{:.precision$}", phase, precision = self.config.precision);
                Ok(format!("p({}) {};", formatted_phase, qubit_str))
            }

            ExtendedGate::RXX(theta) => {
                let formatted_theta =
                    format!("{:.precision$}", theta, precision = self.config.precision);
                Ok(format!("rxx({}) {};", formatted_theta, qubit_str))
            }

            ExtendedGate::RYY(theta) => {
                let formatted_theta =
                    format!("{:.precision$}", theta, precision = self.config.precision);
                Ok(format!("ryy({}) {};", formatted_theta, qubit_str))
            }

            ExtendedGate::RZZ(theta) => {
                let formatted_theta =
                    format!("{:.precision$}", theta, precision = self.config.precision);
                Ok(format!("rzz({}) {};", formatted_theta, qubit_str))
            }

            ExtendedGate::RZX(theta) => {
                let formatted_theta =
                    format!("{:.precision$}", theta, precision = self.config.precision);
                Ok(format!("rzx({}) {};", formatted_theta, qubit_str))
            }

            ExtendedGate::QFT(n) => {
                // QFT decomposition would be complex, for now return a comment
                Ok(format!("// QFT({}) on qubits {}", n, qubit_str))
            }

            ExtendedGate::IQFT(n) => {
                // IQFT decomposition would be complex, for now return a comment
                Ok(format!("// IQFT({}) on qubits {}", n, qubit_str))
            }

            ExtendedGate::Custom { name, .. } => {
                // For custom gates, just use the name
                Ok(format!("{} {};", name, qubit_str))
            }
        }
    }
}

impl Default for QasmExporter {
    fn default() -> Self {
        Self::new()
    }
}

/// QASM import functionality (basic parser)
pub struct QasmImporter;

impl QasmImporter {
    /// Parse a QASM string into a quantum circuit (basic implementation)
    pub fn import(qasm_str: &str) -> Result<QuantumCircuit> {
        let lines: Vec<&str> = qasm_str
            .lines()
            .map(|line| line.trim())
            .filter(|line| !line.is_empty() && !line.starts_with("//"))
            .collect();

        if lines.is_empty() {
            return Err(MyQuatError::circuit_error("Empty QASM input"));
        }

        // Parse header
        let mut line_idx = 0;
        if !lines[line_idx].starts_with("OPENQASM") {
            return Err(MyQuatError::circuit_error("Invalid QASM header"));
        }
        line_idx += 1;

        // Skip include statements
        while line_idx < lines.len() && lines[line_idx].starts_with("include") {
            line_idx += 1;
        }

        // Parse register declarations
        let mut num_qubits = 0;
        let mut num_clbits = 0;

        while line_idx < lines.len() {
            let line = lines[line_idx];
            if line.starts_with("qreg") || line.starts_with("qubit") {
                num_qubits = Self::parse_register_size(line)?;
            } else if line.starts_with("creg") || line.starts_with("bit") {
                num_clbits = Self::parse_register_size(line)?;
            } else {
                break; // Start of gate operations
            }
            line_idx += 1;
        }

        let mut circuit = QuantumCircuit::new(num_qubits, num_clbits);

        // Parse gate operations
        for line in &lines[line_idx..] {
            Self::parse_gate_line(&mut circuit, line)?;
        }

        Ok(circuit)
    }

    /// Parse a single gate line and add to circuit
    fn parse_gate_line(circuit: &mut QuantumCircuit, line: &str) -> Result<()> {
        let line = line.trim_end_matches(';');

        // Single-qubit gates without parameters
        if line.starts_with("h ") {
            let qubit = Self::parse_single_qubit_gate(line)?;
            circuit.h(qubit)?;
        } else if line.starts_with("x ") {
            let qubit = Self::parse_single_qubit_gate(line)?;
            circuit.x(qubit)?;
        } else if line.starts_with("y ") {
            let qubit = Self::parse_single_qubit_gate(line)?;
            circuit.y(qubit)?;
        } else if line.starts_with("z ") {
            let qubit = Self::parse_single_qubit_gate(line)?;
            circuit.z(qubit)?;
        } else if line.starts_with("s ") {
            let qubit = Self::parse_single_qubit_gate(line)?;
            circuit.s(qubit)?;
        } else if line.starts_with("sdg ") {
            let qubit = Self::parse_single_qubit_gate(line)?;
            circuit.sdg(qubit)?;
        } else if line.starts_with("t ") {
            let qubit = Self::parse_single_qubit_gate(line)?;
            circuit.t(qubit)?;
        } else if line.starts_with("tdg ") {
            let qubit = Self::parse_single_qubit_gate(line)?;
            circuit.tdg(qubit)?;
        } else if line.starts_with("id ") || line.starts_with("i ") {
            let qubit = Self::parse_single_qubit_gate(line)?;
            circuit.i(qubit)?;
        }
        // Parameterized single-qubit gates
        else if line.starts_with("rx(") {
            let (angle, qubit) = Self::parse_parameterized_gate(line)?;
            circuit.rx(qubit, Parameter::Float(angle))?;
        } else if line.starts_with("ry(") {
            let (angle, qubit) = Self::parse_parameterized_gate(line)?;
            circuit.ry(qubit, Parameter::Float(angle))?;
        } else if line.starts_with("rz(") {
            let (angle, qubit) = Self::parse_parameterized_gate(line)?;
            circuit.rz(qubit, Parameter::Float(angle))?;
        } else if line.starts_with("p(") || line.starts_with("phase(") {
            let (angle, qubit) = Self::parse_parameterized_gate(line)?;
            circuit.p(qubit, Parameter::Float(angle))?;
        } else if line.starts_with("u1(") {
            let (lambda, qubit) = Self::parse_parameterized_gate(line)?;
            circuit.u1(qubit, Parameter::Float(lambda))?;
        } else if line.starts_with("u2(") {
            let (params, qubit) = Self::parse_multi_param_gate(line, 2)?;
            circuit.u2(
                qubit,
                Parameter::Float(params[0]),
                Parameter::Float(params[1]),
            )?;
        } else if line.starts_with("u3(") || line.starts_with("u(") {
            let (params, qubit) = Self::parse_multi_param_gate(line, 3)?;
            circuit.u3(
                qubit,
                Parameter::Float(params[0]),
                Parameter::Float(params[1]),
                Parameter::Float(params[2]),
            )?;
        }
        // Two-qubit gates
        else if line.starts_with("cx ") || line.starts_with("cnot ") {
            let (control, target) = Self::parse_two_qubit_gate(line)?;
            circuit.cx(control, target)?;
        } else if line.starts_with("cy ") {
            let (control, target) = Self::parse_two_qubit_gate(line)?;
            circuit.cy(control, target)?;
        } else if line.starts_with("cz ") {
            let (control, target) = Self::parse_two_qubit_gate(line)?;
            circuit.cz(control, target)?;
        } else if line.starts_with("ch ") {
            let (control, target) = Self::parse_two_qubit_gate(line)?;
            circuit.ch(control, target)?;
        } else if line.starts_with("swap ") {
            let (q1, q2) = Self::parse_two_qubit_gate(line)?;
            circuit.swap(q1, q2)?;
        }
        // Parameterized two-qubit gates
        else if line.starts_with("crx(") {
            let (angle, control, target) = Self::parse_parameterized_two_qubit_gate(line)?;
            circuit.crx(control, target, Parameter::Float(angle))?;
        } else if line.starts_with("cry(") {
            let (angle, control, target) = Self::parse_parameterized_two_qubit_gate(line)?;
            circuit.cry(control, target, Parameter::Float(angle))?;
        } else if line.starts_with("crz(") {
            let (angle, control, target) = Self::parse_parameterized_two_qubit_gate(line)?;
            circuit.crz(control, target, Parameter::Float(angle))?;
        }
        // Measurement
        else if line.starts_with("measure ") {
            let (qubit, clbit) = Self::parse_measurement(line)?;
            circuit.measure(qubit, clbit)?;
        }
        // Barrier (ignore for now)
        else if line.starts_with("barrier") {
            // Skip barrier instructions
        }
        // Gate definitions and other directives
        else if line.starts_with("gate ") || line.starts_with("opaque ") {
            // Skip custom gate definitions for now
        }

        Ok(())
    }

    /// Parse register size from declaration line
    fn parse_register_size(line: &str) -> Result<usize> {
        // Extract size from patterns like "qreg q[5];" or "qubit[5] q;"
        if let Some(start) = line.find('[') {
            if let Some(end) = line.find(']') {
                let size_str = &line[start + 1..end];
                return size_str
                    .parse()
                    .map_err(|_| MyQuatError::circuit_error("Invalid register size"));
            }
        }
        Err(MyQuatError::circuit_error("Cannot parse register size"))
    }

    /// Parse single qubit gate
    fn parse_single_qubit_gate(line: &str) -> Result<usize> {
        // Extract qubit index from patterns like "h q[0];"
        if let Some(start) = line.find('[') {
            if let Some(end) = line.find(']') {
                let qubit_str = &line[start + 1..end];
                return qubit_str
                    .parse()
                    .map_err(|_| MyQuatError::circuit_error("Invalid qubit index"));
            }
        }
        Err(MyQuatError::circuit_error("Cannot parse qubit index"))
    }

    /// Parse two qubit gate
    fn parse_two_qubit_gate(line: &str) -> Result<(usize, usize)> {
        // Extract qubit indices from patterns like "cx q[0],q[1];"
        let indices: Vec<usize> = line
            .matches(char::is_numeric)
            .filter_map(|s| s.parse().ok())
            .collect();

        if indices.len() >= 2 {
            Ok((indices[0], indices[1]))
        } else {
            Err(MyQuatError::circuit_error("Cannot parse two-qubit gate"))
        }
    }

    /// Parse parameterized single-qubit gate (e.g., "rx(1.5) q[0]")
    fn parse_parameterized_gate(line: &str) -> Result<(f64, usize)> {
        // Extract parameter from parentheses
        if let Some(start) = line.find('(') {
            if let Some(end) = line.find(')') {
                let param_str = &line[start + 1..end];
                let angle: f64 = param_str
                    .trim()
                    .parse()
                    .map_err(|_| MyQuatError::circuit_error("Invalid parameter value"))?;

                // Extract qubit index
                let qubit = Self::parse_single_qubit_gate(&line[end..])?;
                return Ok((angle, qubit));
            }
        }
        Err(MyQuatError::circuit_error(
            "Cannot parse parameterized gate",
        ))
    }

    /// Parse multi-parameter gate (e.g., "u2(1.5, 2.0) q[0]")
    fn parse_multi_param_gate(line: &str, num_params: usize) -> Result<(Vec<f64>, usize)> {
        if let Some(start) = line.find('(') {
            if let Some(end) = line.find(')') {
                let params_str = &line[start + 1..end];
                let params: Result<Vec<f64>> = params_str
                    .split(',')
                    .map(|s| {
                        s.trim()
                            .parse()
                            .map_err(|_| MyQuatError::circuit_error("Invalid parameter value"))
                    })
                    .collect();
                let params = params?;

                if params.len() != num_params {
                    return Err(MyQuatError::circuit_error(format!(
                        "Expected {} parameters, got {}",
                        num_params,
                        params.len()
                    )));
                }

                let qubit = Self::parse_single_qubit_gate(&line[end..])?;
                return Ok((params, qubit));
            }
        }
        Err(MyQuatError::circuit_error(
            "Cannot parse multi-parameter gate",
        ))
    }

    /// Parse parameterized two-qubit gate (e.g., "crx(1.5) q[0],q[1]")
    fn parse_parameterized_two_qubit_gate(line: &str) -> Result<(f64, usize, usize)> {
        if let Some(start) = line.find('(') {
            if let Some(end) = line.find(')') {
                let param_str = &line[start + 1..end];
                let angle: f64 = param_str
                    .trim()
                    .parse()
                    .map_err(|_| MyQuatError::circuit_error("Invalid parameter value"))?;

                let (control, target) = Self::parse_two_qubit_gate(&line[end..])?;
                return Ok((angle, control, target));
            }
        }
        Err(MyQuatError::circuit_error(
            "Cannot parse parameterized two-qubit gate",
        ))
    }

    /// Parse measurement operation (e.g., "measure q[0] -> c[0]")
    fn parse_measurement(line: &str) -> Result<(usize, usize)> {
        // Extract qubit and classical bit indices
        let indices: Vec<usize> = line
            .matches(char::is_numeric)
            .filter_map(|s| s.parse().ok())
            .collect();

        if indices.len() >= 2 {
            Ok((indices[0], indices[1]))
        } else {
            Err(MyQuatError::circuit_error("Cannot parse measurement"))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::f64::consts::PI;

    #[test]
    fn test_qasm_config() {
        let config = QasmConfig::default();
        assert_eq!(config.version, QasmVersion::V2_0);
        assert!(config.include_comments);
        assert_eq!(config.precision, 6);
    }

    #[test]
    fn test_qasm_version_display() {
        assert_eq!(QasmVersion::V2_0.to_string(), "2.0");
        assert_eq!(QasmVersion::V3_0.to_string(), "3.0");
    }

    #[test]
    fn test_simple_circuit_export_v2() {
        let mut circuit = QuantumCircuit::new(2, 2);
        circuit.h(0).unwrap();
        circuit.cx(0, 1).unwrap();
        circuit.measure(0, 0).unwrap();
        circuit.measure(1, 1).unwrap();

        let exporter = QasmExporter::new();
        let qasm = exporter.export(&circuit).unwrap();

        assert!(qasm.contains("OPENQASM 2.0"));
        assert!(qasm.contains("qreg q[2]"));
        assert!(qasm.contains("creg c[2]"));
        assert!(qasm.contains("h q[0]"));
        assert!(qasm.contains("cx q[0],q[1]"));
        assert!(qasm.contains("measure q[0] -> c[0]"));
    }

    #[test]
    fn test_simple_circuit_export_v3() {
        let mut circuit = QuantumCircuit::new(2, 2);
        circuit.h(0).unwrap();
        circuit.cx(0, 1).unwrap();

        let config = QasmConfig {
            version: QasmVersion::V3_0,
            ..QasmConfig::default()
        };
        let exporter = QasmExporter::with_config(config);
        let qasm = exporter.export(&circuit).unwrap();

        assert!(qasm.contains("OPENQASM 3.0"));
        assert!(qasm.contains("qubit[2] q"));
        assert!(qasm.contains("bit[2] c"));
        assert!(qasm.contains("h q[0]"));
        assert!(qasm.contains("cx q[0], q[1]"));
    }

    #[test]
    fn test_parametric_gates_export() {
        let mut circuit = QuantumCircuit::new(1, 0);
        circuit.rx(0, Parameter::new_float(PI / 2.0)).unwrap();
        circuit.ry(0, Parameter::new_float(PI / 4.0)).unwrap();

        let exporter = QasmExporter::new();
        let qasm = exporter.export(&circuit).unwrap();

        assert!(qasm.contains("rx(1.570796) q[0]"));
        assert!(qasm.contains("ry(0.785398) q[0]"));
    }

    #[test]
    fn test_qasm_import_basic() {
        let qasm_str = r#"
            OPENQASM 2.0;
            include "qelib1.inc";
            qreg q[2];
            creg c[2];
            h q[0];
            cx q[0],q[1];
        "#;

        let circuit = QasmImporter::import(qasm_str).unwrap();
        assert_eq!(circuit.num_qubits(), 2);
        assert_eq!(circuit.num_clbits(), 2);
        assert_eq!(circuit.size(), 2); // H + CX
    }

    #[test]
    fn test_format_parameter() {
        let exporter = QasmExporter::new();

        let float_param = Parameter::new_float(3.14159);
        assert_eq!(exporter.format_parameter(&float_param).unwrap(), "3.141590");

        let symbol_param = Parameter::new_symbol("theta");
        assert_eq!(exporter.format_parameter(&symbol_param).unwrap(), "theta");
    }

    #[test]
    fn test_unsupported_gate_error() {
        let circuit = QuantumCircuit::new(1, 0);
        // Assuming we have some unsupported gate

        let exporter = QasmExporter::new();
        let result = exporter.export(&circuit);
        assert!(result.is_ok()); // Empty circuit should be fine
    }

    #[test]
    fn test_extended_gate_definitions() {
        let config = QasmConfig {
            include_extended_gates: true,
            ..QasmConfig::default()
        };
        let exporter = QasmExporter::with_config(config);

        let circuit = QuantumCircuit::new(2, 0);
        let qasm = exporter.export(&circuit).unwrap();

        // Check that extended gate definitions are included
        assert!(qasm.contains("gate sqrtx"));
        assert!(qasm.contains("gate rxx"));
        assert!(qasm.contains("gate ryy"));
        assert!(qasm.contains("gate rzz"));
    }

    #[test]
    fn test_extended_gate_conversion() {
        use crate::circuit::Qubit;
        use crate::gates_extended::ExtendedGate;

        let exporter = QasmExporter::new();

        // Test square root gates
        let sqrt_x = ExtendedGate::SqrtX;
        let qubits = vec![Qubit::new(0)];
        let qasm = exporter.extended_gate_to_qasm(&sqrt_x, &qubits).unwrap();
        assert_eq!(qasm, "sqrtx q[0];");

        // Test parametric gates
        let rxx = ExtendedGate::RXX(1.57);
        let qubits = vec![Qubit::new(0), Qubit::new(1)];
        let qasm = exporter.extended_gate_to_qasm(&rxx, &qubits).unwrap();
        assert!(qasm.contains("rxx(1.570000) q[0],q[1];"));

        // Test global phase
        let global_phase = ExtendedGate::GlobalPhase(0.5);
        let qubits = vec![];
        let qasm = exporter
            .extended_gate_to_qasm(&global_phase, &qubits)
            .unwrap();
        assert!(qasm.contains("Global phase"));
    }

    #[test]
    fn test_extended_gate_v3_format() {
        let config = QasmConfig {
            version: QasmVersion::V3_0,
            include_extended_gates: true,
            ..QasmConfig::default()
        };
        let exporter = QasmExporter::with_config(config);

        let circuit = QuantumCircuit::new(2, 0);
        let qasm = exporter.export(&circuit).unwrap();

        // Check QASM 3.0 specific formatting
        assert!(qasm.contains("OPENQASM 3.0"));
        assert!(qasm.contains("π")); // Should use π symbol in v3.0
    }

    #[test]
    fn test_custom_gate_export() {
        use crate::circuit::Qubit;
        use crate::gates_extended::ExtendedGate;

        let exporter = QasmExporter::new();

        let custom_gate = ExtendedGate::Custom {
            name: "my_gate".to_string(),
            matrix_real: vec![vec![1.0, 0.0], vec![0.0, 1.0]],
            matrix_imag: vec![vec![0.0, 0.0], vec![0.0, 0.0]],
            num_qubits: 1,
            parameters: vec![],
        };

        let qubits = vec![Qubit::new(0)];
        let qasm = exporter
            .extended_gate_to_qasm(&custom_gate, &qubits)
            .unwrap();
        assert_eq!(qasm, "my_gate q[0];");
    }
}
